### ISSUE TITLE
Flutterflow build run keeps loading for long

### ISSUE THREAD

**Issue by tarorg** [imodoye94/taniDB#1]
![image](https://github.com/imodoye94/taniDB/assets/78031947/558ef8d4-7af8-42f3-b4b8-d389df6dafea)

**Comment by imodoye94** [comment]
Hi @wetarorg check out the docs here 

https://docs.tanidb.dev/fundamentals/getting-started/testing-your-app

You need to test your app in RUN Mode not test mode. Due to the sandboxed nature of Test mode and random port number assignment, tani can't reliably connect to Indexed DB in Flutterflow Test mode.

I will now close this issue. If you run into any problems in Run Mode, you can open another issue here. Or reach me on the community forum. Best wishes.
